### PR TITLE
[ISSUE #297] return headers in login callback for authentication

### LINKED ISSUE #297: auth.config().login doesn't return headers
I'm trying to implement OTP code.
I want to show different messages to the user based on the [OTP header](https://developer.github.com/v3/auth/#working-with-two-factor-authentication), but on authentication fail (first without an OTP), I can't know what types of OTP to show.

I tried checking the error messages but nothing relevant there.
Also tried the following structure for the callback as the API suggested (`login(..., function(err, data, headers) {})`), but looks like `login` works with `login(..., function(err, id, token) {})` instead

### PR DESCRIPTION
**Pull request by Thatkookooguy**
resolves #297

Let me know if you want me to do something similar in the `web` login flow

basically, changed the login function to this:
```js
var scopes = {
  'add_scopes': ['user', 'repo', 'gist'],
  'note': 'admin script'
};

github.auth.config({
  username: 'pksunkara',
  password: 'password'
}).login(scopes, function (err, id, token, headers) {
  console.log(id, token);
});
```

### CODE REVIEW

File: src/octonode/auth.coffee [hunk 1]
```diff
@@ -63,13 +63,13 @@ auth = module.exports =
 
       request options, (err, res, body) ->
         if err?
-          callback err
+          callback(err, null, null, res.headers)
```
Comment (pksunkara) [inline src/octonode/auth.coffee]: What happens when `res` doesn't exist or `res.headers` doesn't exist.

**Comment by pksunkara** [comment]
Yeah, please add it to the other flow too. Thanks.

File: src/octonode/auth.coffee (hunk 1 above)
Comment (Thatkookooguy) [reply src/octonode/auth.coffee]: changed it to return an empty object if headers doesn't exist
